#!/usr/bin/env python3
"""Rebuild src/surge_fx_table.inc: what Wavelength needs to turn a Surge .srgfx effect preset into
Surge XT Effects' state.

A .srgfx holds Surge's plain parameter values in storage order; Surge XT Effects stores values
normalized 0..1 (integers as 0.005 + 0.99 x) in its own slot order. This script
  1. measures every effect type's parameter ranges and integer-ness by setting the Surge XT synth's
     "FX A1" parameters to 0, 0.5 and 1 and reading back the plain values its patch stores, and
  2. reads each effect's layout offsets (posy_offset) from Surge's source at TAG, which Surge XT
     Effects sorts its slots by (i * 2 + posy_offset; unused parameters last).

usage: scripts/surge-fx-table.py [--tag release_xt_1.0.0] [--wavelength build/wavelength] > src/surge_fx_table.inc
Needs Surge XT (VST3) installed and network access to raw.githubusercontent.com. Runs one plugin
process at a time (about 3 minutes).
"""
import argparse, json, os, re, struct, subprocess, sys, tempfile, urllib.request

ap = argparse.ArgumentParser()
ap.add_argument('--tag', default='release_xt_1.0.0')
ap.add_argument('--wavelength', default=os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'build', 'wavelength'))
a = ap.parse_args()
W, TMP = a.wavelength, tempfile.mkdtemp(prefix='surgefx-')
SYN_IDS = [885066848 + k for k in range(10)] + [1667268591, 1667268592]   # Surge XT "FX A1 Param 1..12"
FILES = {1: 'DelayEffect', 2: 'Reverb1Effect', 3: 'PhaserEffect', 4: 'RotarySpeakerEffect', 5: 'DistortionEffect',
         6: 'ParametricEQ3BandEffect', 7: 'FrequencyShifterEffect', 8: 'ConditionerEffect', 9: 'ChorusEffectImpl',
         10: 'VocoderEffect', 11: 'Reverb2Effect', 12: 'FlangerEffect', 13: 'RingModulatorEffect', 14: 'airwindows/AirWindowsEffect',
         15: 'chowdsp/NeuronEffect', 16: 'GraphicEQ11BandEffect', 17: 'ResonatorEffect', 18: 'chowdsp/CHOWEffect',
         19: 'chowdsp/ExciterEffect', 20: 'BBDEnsembleEffect', 21: 'CombulatorEffect', 22: 'NimbusEffect', 23: 'chowdsp/TapeEffect',
         24: 'TreemonsterEffect', 25: 'WaveShaperEffect', 26: 'MSToolEffect', 27: 'chowdsp/SpringReverbEffect'}

def run(*args): return subprocess.run([W, *args], capture_output=True, text=True)
def comp(path):
    d = open(path, 'rb').read(); lo = struct.unpack('<q', d[40:48])[0]; n = struct.unpack('<i', d[lo+4:lo+8])[0]
    for i in range(n):
        e = d[lo+8+i*20:lo+28+i*20]; off, sz = struct.unpack('<qq', e[4:])
        if e[:4] == b'Comp': return d[off:off+sz]
def split(c):   # Surge patch: "sub3" + u32 xml size + 6 u32 wavetable sizes, xml, wavetables
    xs = struct.unpack('<I', c[4:8])[0]; return c[:32], c[32:32+xs].rstrip(b'\0').decode(), c[32+xs:]
def join(h, x, t):
    b = x.encode() + b'\0'; h = bytearray(h); h[4:8] = struct.pack('<I', len(b)); return bytes(h) + b + t

run('state', 'save', 'vst3:Surge XT', '--out', TMP + '/base.vstpreset')
BASE = comp(TMP + '/base.vstpreset')
def patch(T):
    h, x, t = split(BASE)
    x = re.sub(r'<fx1_(type|p\d+)[^>]*/>', '', x).replace('</parameters>', '<fx1_type type="0" value="%d" /></parameters>' % T)
    return join(h, x, t)
def synth(T, v):
    open(TMP + '/in.bin', 'wb').write(patch(T))
    args = ['state', 'save', 'vst3:Surge XT', '--state', TMP + '/in.bin', '--format', 'raw', '--out', TMP + '/out.vstpreset']
    for k in SYN_IDS: args += ['--set', '#%d=%r' % (k, v)]
    run(*args)
    x = split(comp(TMP + '/out.vstpreset'))[1]
    return [re.search(r'<fx1_p%d type="(\d)" value="([^"]*)"' % i, x) for i in range(12)]
def names(T):
    open(TMP + '/in.bin', 'wb').write(patch(T))
    ps = {p['id']: p['name'] for p in json.loads(run('params', 'vst3:Surge XT', '--state', TMP + '/in.bin', '--format', 'raw', '--all', '--json').stdout)['params']}
    return [ps.get(i, '').replace('FX A1 ', '') for i in SYN_IDS]
def source(path):
    t = ''
    for ext in ('.h', '.cpp'):
        try: t += urllib.request.urlopen('https://raw.githubusercontent.com/surge-synthesizer/surge/%s/src/common/dsp/effects/%s%s' % (a.tag, path, ext)).read().decode()
        except Exception: pass
    if path == 'ChorusEffectImpl': t += source('ChorusEffect')
    t = re.sub(r'/\*.*?\*/', '', t, flags=re.S); return re.sub(r'//[^\n]*', '', t)
def enum_of(t, members):
    for m in re.finditer(r'enum\s+\w*\s*\{([^}]*)\}', t):
        ms = [x.strip().split('=')[0].strip() for x in m.group(1).split(',') if x.strip()]
        if all(n in ms for n in members): return {n: i for i, n in enumerate(ms)}

print('// Generated by scripts/surge-fx-table.py (--tag %s): each Surge effect type\'s parameters in storage' % a.tag)
print('// order (the order .srgfx files use) as {integer, min, max}, and remap[slot] = the storage parameter')
print('// behind Surge XT Effects\' parameter slot. Unused parameters have min == max. Ranges were measured')
print('// through the Surge XT synth; the slot order is Surge XT Effects\' sort of each effect\'s layout offsets.')
f = lambda v: repr(float(v)) + 'f'
for T, path in FILES.items():
    nm, lo, hi = names(T), synth(T, 0.0), synth(T, 1.0)
    unused = [] if T == 14 else [i for i in range(12) if not lo[i] or re.fullmatch(r'Param \d+|', nm[i])]
    t = source(path)
    asg = re.findall(r'p\[(\w+)\]\.posy_offset\s*=\s*(-?\w+)\s*;', t)
    en = enum_of(t, [n for n, _ in asg]) if asg and not any(n.isdigit() or n == 'i' for n, _ in asg) else None
    key = {en[n]: en[n] * 2 + int(v) for n, v in asg if int(v) != 0} if T != 14 and en and all(v.lstrip('-').isdigit() for _, v in asg) \
        else {i: i for i in range(12)}   # loops and increasing offsets keep storage order
    used = [i for i in range(12) if i in key and i not in unused]
    remap = sorted(used, key=lambda i: (key[i], i)) + [i for i in range(12) if i not in used]
    ps = []
    for i in range(12):
        if T == 14 and i > 0: ps.append('{0, 0.0f, 1.0f}')   # Airwindows: the chosen effect's parameters are 0..1
        elif i in unused: ps.append('{0, 0.0f, 0.0f}')
        else: ps.append('{%d, %s, %s}' % (lo[i].group(1) == '0', f(lo[i].group(2)), f(hi[i].group(2))))
    print('{%d, {%s},\n    {%s}},' % (T, ', '.join(map(str, remap)), ', '.join(ps)))
    print('type', T, path, file=sys.stderr, flush=True)
