# Turns every file under UI_DIR into a byte array in OUT (a C++ source), so `wavelength serve`
# carries its web UI inside the binary. Run by the build whenever a UI file changes.
file(GLOB_RECURSE files RELATIVE "${UI_DIR}" "${UI_DIR}/*")
list(SORT files)
set(out "// generated from ui/ by cmake/embed-ui.cmake; do not edit\n#include <cstddef>\nnamespace wl {\nstruct UiAsset { const char *path; const unsigned char *data; size_t size; };\n")
set(table "")
set(i 0)
foreach(f ${files})
  if(f MATCHES "(^|/)\\.")
    continue()
  endif()
  file(READ "${UI_DIR}/${f}" hex HEX)
  string(LENGTH "${hex}" n)
  math(EXPR size "${n} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(APPEND out "static const unsigned char a${i}[] = {${bytes}0};\n")
  string(APPEND table "  {\"${f}\", a${i}, ${size}},\n")
  math(EXPR i "${i} + 1")
endforeach()
string(APPEND out "extern const UiAsset kUiAssets[] = {\n${table}  {nullptr, nullptr, 0}};\nextern const size_t kUiAssetCount = ${i};\n} // namespace wl\n")
file(WRITE "${OUT}" "${out}")
