/* Arrangement editor for the Wavelength live viewer.
 *
 * Read-only on the music (songs are generated by their make-job.py, so edits here would be lost):
 * you look, listen, loop and select, then leave comments pinned to bars, tracks and notes. They go to
 * the song's review.json, which the agent reads and turns into changes.
 *
 * Uses the page's globals: state, audio, tempoFn, hue, esc, fmtTime, stemFor, toggleSolo, setSrc.
 */
(() => {
	const HEAD = 210, RULER = 24, SECT = 20, CHORD = 24, TOPH = RULER + SECT + CHORD, LANE = 42, LANE_OPEN = 170;
	const NAMES = ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B'];
	const keyName = k => NAMES[((k % 12) + 12) % 12] + (Math.floor(k / 12) - 1);
	// canvas colours: a theme token (hex) at some opacity (canvas fillStyle can't be trusted with color-mix())
	const alpha = (hex, a) => { const m = String(hex).trim().match(/^#([0-9a-f]{6})$/i); if (!m) return hex; const n = parseInt(m[1], 16); return `rgba(${n >> 16},${(n >> 8) & 255},${n & 255},${a})`; };
	const E = {
		zoom: 26, dirty: true, data: null, harmony: null, comments: [], expanded: new Set(), hover: null,
		sel: { b0: null, b1: null, tracks: new Set(), notes: [] }, loop: false, drag: null, userScrollAt: 0, follow: true,
	};
	let dlg, scroller, canvas, space, tip;

	/* ---------- markup ---------- */
	function build() {
		dlg = document.createElement('dialog');
		dlg.className = 'ed';
		dlg.innerHTML = `
		<div class="ed-grid">
			<div class="ed-bar">
				<h3 id="ed-title"></h3>
				<button class="ed-btn play" id="ed-play" title="Play / pause (Space)"><svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" id="ed-playicon"><path d="M6 4l14 8-14 8z"/></svg></button>
				<div class="ed-clock" id="ed-clock">0:00<small>bar 1.1</small></div>
				<button class="ed-btn" id="ed-loop" title="Loop the selected bars (L)">
					<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M17 2l4 4-4 4"/><path d="M3 11V9a3 3 0 0 1 3-3h15"/><path d="M7 22l-4-4 4-4"/><path d="M21 13v2a3 3 0 0 1-3 3H3"/></svg>Loop</button>
				<button class="ed-btn on" id="ed-follow" title="Keep the playhead in view">Follow</button>
				<span class="ed-group"><button class="ed-btn" id="ed-zout" title="Zoom out (-)">−</button><button class="ed-btn" id="ed-fit" title="Whole song (F)">Fit</button><button class="ed-btn" id="ed-zin" title="Zoom in (+)">+</button></span>
				<span class="ed-legend" id="ed-legend"></span>
				<span class="ed-status" id="ed-status"></span>
				<span class="sp"></span>
				<select id="ed-audio" title="What plays"></select>
				<button class="ed-btn" id="ed-close" title="Close (Esc)">✕</button>
			</div>
			<div class="ed-main">
				<div class="ed-scroll" id="ed-scroll"><canvas id="ed-canvas"></canvas><div class="ed-space" id="ed-space"></div></div>
				<div class="ed-tip" id="ed-tip" hidden></div>
			</div>
			<div class="ed-side">
				<section>
					<h4>Selection <span class="r"><button class="ed-btn" id="ed-clear" style="height:22px;font-size:11px">Clear</button></span></h4>
					<div class="ed-ref none" id="ed-ref">Drag across the ruler to pick bars, click a track name, click or drag over notes.</div>
					<div class="ed-actions">
						<button class="ed-btn amber" id="ed-preview" disabled title="Render the selected bars through the mix and loop them (P)">▶ Preview these bars</button>
						<button class="ed-btn" id="ed-sloop" disabled>Loop these bars</button>
						<button class="ed-btn" id="ed-solo" disabled>Solo track</button>
						<button class="ed-btn" id="ed-copy" disabled>Copy reference</button>
					</div>
				</section>
				<section>
					<h4>Comment for the agent</h4>
					<textarea id="ed-text" placeholder="What should change here? (Cmd+Enter to save)"></textarea>
					<div class="ed-actions"><button class="ed-btn primary" id="ed-save">Save comment</button></div>
					<div class="ed-hint">Saved to review.json in the song folder with the bars, tracks, notes and time you selected.</div>
				</section>
				<h4 style="padding:12px 14px 0;margin:0">Comments <span class="r" id="ed-count"></span></h4>
				<div class="ed-list" id="ed-list"></div>
			</div>
		</div>`;
		document.body.appendChild(dlg);
		scroller = dlg.querySelector('#ed-scroll'); canvas = dlg.querySelector('#ed-canvas'); space = dlg.querySelector('#ed-space'); tip = dlg.querySelector('#ed-tip');
		const on = (id, ev, fn) => dlg.querySelector(id).addEventListener(ev, fn);
		on('#ed-close', 'click', () => dlg.close());
		on('#ed-play', 'click', () => audio.paused ? audio.play() : audio.pause());
		on('#ed-loop', 'click', () => setLoop(!E.loop));
		on('#ed-sloop', 'click', () => { setLoop(true); seekBeat(E.sel.b0, true); });
		on('#ed-preview', 'click', previewSelection);
		on('#ed-follow', 'click', () => { E.follow = !E.follow; dlg.querySelector('#ed-follow').classList.toggle('on', E.follow); });
		on('#ed-zin', 'click', () => zoomAt(1.4));
		on('#ed-zout', 'click', () => zoomAt(1 / 1.4));
		on('#ed-fit', 'click', fit);
		on('#ed-clear', 'click', () => { clearSel(); });
		on('#ed-copy', 'click', () => navigator.clipboard?.writeText(reference().text));
		on('#ed-solo', 'click', () => {   // with bars selected: a quick preview of this track in those bars; else the whole track
			const i = [...E.sel.tracks][0] ?? E.sel.notes[0]?.t;
			if (i == null) return;
			if (E.sel.b0 != null) previewSelection([E.data.tracks[i].name]); else toggleSolo(i);
			syncAudioSelect(); dirty();
		});
		on('#ed-save', 'click', save);
		on('#ed-list', 'click', e => {   // a comment: jump to what it points at; its buttons change it
			const c = e.target.closest('.ed-c'); if (!c) return;
			const act = e.target.closest('button')?.dataset.act, cm = E.comments.find(x => x.id === c.dataset.id);
			if (!cm) return;
			if (act === 'status') return op({ op: 'status', id: cm.id, status: cm.status === 'done' ? 'open' : 'done' });
			if (act === 'delete') { if (confirm('Delete this comment?')) op({ op: 'delete', id: cm.id }); return; }
			const d = E.data;
			E.sel = { b0: cm.beats?.[0] ?? null, b1: cm.beats?.[1] ?? null, tracks: new Set((cm.tracks || []).map(n => d.tracks.findIndex(t => t.name === n)).filter(i => i >= 0)), notes: [] };
			(cm.notes || []).forEach(n => {
				const ti = d.tracks.findIndex(t => t.name === n.track); if (ti < 0) return;
				const ni = d.tracks[ti].beatsNotes.findIndex(x => Math.abs(x[0] - n.beat) < 1e-3 && x[2] === n.midi);
				if (ni >= 0) E.sel.notes.push({ t: ti, n: ni });
			});
			if (cm.beats) { scroller.scrollLeft = Math.max(0, cm.beats[0] * E.zoom - 120); seekBeat(cm.beats[0], false); }
			selChanged();
		});
		on('#ed-text', 'keydown', e => { if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) { e.preventDefault(); save(); } });
		on('#ed-audio', 'change', e => {
			const v = e.target.value;
			if (v.startsWith('stem:')) toggleSolo(+v.slice(5), 'dry');
			else if (v.startsWith('solo:')) toggleSolo(+v.slice(5), 'mix');
			else if (v !== 'preview') { $('#audiosel').value = v; backToMix(songSecNow(), !audio.paused); }
			dirty();
		});
		dlg.addEventListener('cancel', e => { if (E.sel.b0 != null || E.sel.tracks.size || E.sel.notes.length) { e.preventDefault(); clearSel(); } });
		dlg.addEventListener('close', () => { E.loop = false; });
		scroller.addEventListener('scroll', () => { E.userScrollAt = performance.now(); dirty(); });
		scroller.addEventListener('wheel', e => {
			if (!(e.ctrlKey || e.metaKey)) return;
			e.preventDefault();
			zoomAt(e.deltaY < 0 ? 1.15 : 1 / 1.15, e.clientX - scroller.getBoundingClientRect().left);
		}, { passive: false });
		canvas.addEventListener('mousedown', down);
		addEventListener('mousemove', move);
		addEventListener('mouseup', up);
		canvas.addEventListener('mouseleave', () => { E.hover = null; tip.hidden = true; dirty(); });
		canvas.addEventListener('dblclick', e => { const p = pos(e); if (p.x > HEAD && p.y < TOPH) seekBeat(beatAt(p.x), true); });
		dlg.addEventListener('keydown', key);
		new ResizeObserver(() => dirty()).observe(scroller);
		audio.addEventListener('play', icon); audio.addEventListener('pause', icon);
	}
	const $d = s => dlg.querySelector(s);
	function icon() { if (dlg) $d('#ed-playicon').innerHTML = audio.paused ? '<path d="M6 4l14 8-14 8z"/>' : '<path d="M6 4h4v16H6zM14 4h4v16h-4z"/>'; }

	/* ---------- data ---------- */
	function prepare() {
		const job = state.song?.job;
		if (!job) { E.data = null; return; }
		const toSec = tempoFn(job.tempo);
		const ts = job.timeSignature || [4, 4], bpb = ts[0] * 4 / ts[1];
		const secToBeat = s => { let lo = 0, hi = 1; while (toSec(hi) < s) hi *= 2; for (let i = 0; i < 50; i++) { const m = (lo + hi) / 2; toSec(m) < s ? lo = m : hi = m; } return (lo + hi) / 2; };
		const tracks = job.tracks.map((t, i) => {
			const notes = t.notes.map(n => n[4] ? [secToBeat(n[0]), secToBeat(n[0] + n[1]) - secToBeat(n[0]), n[2], n[3]] : [n[0], n[1], n[2], n[3]]);
			const keys = notes.map(n => n[2]);
			const lufs = state.song.report?.tracks?.find(r => r.name === t.name)?.lufs;
			return { ...t, idx: i, beatsNotes: notes, lo: keys.length ? Math.min(...keys) : 60, hi: keys.length ? Math.max(...keys) : 60, lufs };
		});
		const endBeat = Math.max(bpb, ...tracks.flatMap(t => t.beatsNotes.map(n => n[0] + n[1])));
		const leadIn = state.song.report?.leadIn ?? job.leadIn ?? 0;
		const markers = (job.markers || []).map(m => ({ name: m.name, beat: +m.beat || 0 })).sort((a, b) => a.beat - b.beat);
		E.data = { tracks, bpb, toSec, secToBeat, endBeat, bars: Math.ceil(endBeat / bpb), leadIn, markers };
	}
	async function loadExtras() {
		const slug = state.slug;
		const [h, r] = await Promise.all([
			fetch('api/harmony?song=' + encodeURIComponent(slug)).then(r => r.json()).catch(() => null),
			fetch('api/review?song=' + encodeURIComponent(slug)).then(r => r.json()).catch(() => ({ comments: [] })),
		]);
		if (slug !== state.slug) return;
		E.harmony = h && h.ok ? h : null;
		E.comments = r.comments || [];
		renderComments(); legend(); badge(); dirty();
	}

	/* ---------- geometry ---------- */
	const laneH = i => E.expanded.has(i) ? LANE_OPEN : LANE;
	function laneTop(i) { let y = TOPH; for (let k = 0; k < i; k++) y += laneH(k); return y; }
	function laneAt(y) { let top = TOPH; for (let i = 0; i < E.data.tracks.length; i++) { const h = laneH(i); if (y >= top && y < top + h) return { i, top, h }; top += h; } return null; }
	const X = b => HEAD + b * E.zoom - scroller.scrollLeft;
	const beatAt = x => Math.max(0, (x - HEAD + scroller.scrollLeft) / E.zoom);
	function pos(e) { const r = canvas.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top, cx: e.clientX, cy: e.clientY }; }
	// y of a key inside a lane: collapsed lanes squeeze the track's range, open lanes are a piano roll
	function keyGeom(t, top, h) {
		const open = E.expanded.has(t.idx);
		const lo = open ? t.lo - 2 : t.lo, hi = open ? t.hi + 2 : t.hi, range = Math.max(open ? 14 : 12, hi - lo + 1);
		const pad = open ? 6 : 5, ih = h - pad * 2, row = open ? ih / range : 3;
		const y = k => open ? top + pad + (hi - k) * row + (ih - (hi - lo + 1) * row) / 2 : top + pad + ih - ((k - lo + (range - (hi - lo)) / 2) / range) * (ih - 3) - 3;
		return { y, row: open ? Math.max(2, row - 1) : 3, lo, hi, open };
	}
	const barOf = b => Math.floor(b / E.data.bpb + 1e-9) + 1;
	// bar.beat, plus .sixteenth when off the beat (DAW style): 42.3 = bar 42 beat 3, 42.3.3 = its third 16th
	const barBeat = b => {
		const bar = barOf(b), inBar = Math.round((b - (bar - 1) * E.data.bpb) * 1000) / 1000, beat = Math.floor(inBar + 1e-9), frac = inBar - beat;
		if (frac < 1e-6) return `${bar}.${beat + 1}`;
		const six = frac * 4;
		return Math.abs(six - Math.round(six)) < 1e-6 ? `${bar}.${beat + 1}.${Math.round(six) + 1}` : `${bar}.${beat + 1}+${+frac.toFixed(3)}`;
	};
	const audioBeat = () => E.data.secToBeat(Math.max(0, songSecNow()));
	function seekBeat(b, play) { if (!audio.src) return; seekSongSec(E.data.toSec(b), play); dirty(); }

	/* ---------- drawing ---------- */
	function dirty() { E.dirty = true; }
	function sizeSpace() {
		const d = E.data; if (!d) return;
		let h = TOPH; d.tracks.forEach((t, i) => h += laneH(i));
		space.style.width = (HEAD + d.endBeat * E.zoom + 60) + 'px';
		space.style.height = (h + 30) + 'px';
	}
	function draw() {
		const d = E.data, w = scroller.clientWidth, h = scroller.clientHeight, dpr = devicePixelRatio || 1;
		if (canvas.width !== w * dpr || canvas.height !== h * dpr) { canvas.width = w * dpr; canvas.height = h * dpr; canvas.style.width = w + 'px'; canvas.style.height = h + 'px'; }
		const g = canvas.getContext('2d'), css = getComputedStyle(document.documentElement), v = n => css.getPropertyValue(n).trim();
		g.setTransform(dpr, 0, 0, dpr, 0, 0);
		g.fillStyle = v('--panel'); g.fillRect(0, 0, w, h);
		if (!d) { g.fillStyle = v('--muted'); g.font = '13px "Instrument Sans", sans-serif'; g.fillText('No job.json yet.', 20, 40); return; }
		const sy = scroller.scrollTop, bpb = d.bpb;
		const b0 = Math.max(0, beatAt(HEAD)), b1 = beatAt(w);
		const accent = v('--accent'), muted = v('--muted'), line = v('--line'), text = v('--text');

		// ---- lanes (clipped below the top rows and right of the headers) ----
		g.save(); g.beginPath(); g.rect(HEAD, TOPH, w - HEAD, h - TOPH); g.clip();
		let top = TOPH - sy;
		d.tracks.forEach((t, i) => {
			const lh = laneH(i);
			if (top + lh > TOPH && top < h) {
				const selT = E.sel.tracks.has(i);
				g.fillStyle = selT ? alpha(accent, 0.08) : i % 2 ? v('--lane') : 'transparent';
				g.fillRect(HEAD, top, w - HEAD, lh);
				const kg = keyGeom(t, top, lh);
				if (kg.open) {   // piano-roll rows: black keys shaded, C lines
					for (let k = kg.lo; k <= kg.hi; k++) {
						const y = kg.y(k), bk = [1, 3, 6, 8, 10].includes(((k % 12) + 12) % 12);
						if (bk) { g.fillStyle = v('--lane'); g.fillRect(HEAD, y, w - HEAD, kg.row + 1); }
						if (k % 12 === 0) { g.fillStyle = line; g.fillRect(HEAD, y + kg.row + 1, w - HEAD, 1); }
					}
				}
				const col = hue(i);
				for (let n = 0; n < t.beatsNotes.length; n++) {
					const [s, len, k, vel] = t.beatsNotes[n];
					if (s + len < b0 || s > b1) continue;
					const x = X(s), nw = Math.max(2, len * E.zoom - 1), y = kg.y(k);
					const chosen = E.sel.notes.some(q => q.t === i && q.n === n);
					g.globalAlpha = t.mute ? .3 : .4 + .6 * Math.min(1, vel);
					g.fillStyle = col;
					g.fillRect(x, y, nw, kg.row);
					if (chosen) { g.globalAlpha = 1; g.strokeStyle = text; g.lineWidth = 1.5; g.strokeRect(x - 1, y - 1, nw + 2, kg.row + 2); }
					if (kg.open && nw > 26 && kg.row >= 8) { g.globalAlpha = .9; g.fillStyle = '#000'; g.font = '9px "Instrument Sans", sans-serif'; g.fillText(keyName(k), x + 2, y + kg.row - 1.5); }
				}
				g.globalAlpha = 1;
				g.fillStyle = line; g.fillRect(HEAD, top + lh - 1, w - HEAD, 1);
			}
			top += lh;
		});
		// grid over the lanes
		gridLines(g, b0, b1, TOPH, h, v);
		g.restore();

		// ---- selection band ----
		if (E.sel.b0 != null) {
			const x0 = Math.max(HEAD, X(E.sel.b0)), x1 = X(E.sel.b1);
			if (x1 > HEAD) {
				g.fillStyle = alpha(accent, 0.14); g.fillRect(x0, 0, x1 - x0, h);
				g.fillStyle = accent; g.fillRect(x0, 0, 1.5, h); g.fillRect(x1 - 1.5, 0, 1.5, h);
			}
		}

		// ---- top rows: ruler, sections, chords ----
		g.save(); g.beginPath(); g.rect(HEAD, 0, w - HEAD, TOPH); g.clip();
		g.fillStyle = v('--panel-2'); g.fillRect(HEAD, 0, w - HEAD, TOPH);
		const barPx = bpb * E.zoom, every = [1, 2, 4, 8, 16, 32].find(n => n * barPx >= 34) || 64;
		g.font = '11px "JetBrains Mono", monospace'; g.textBaseline = 'middle';
		for (let bar = Math.floor(b0 / bpb); bar * bpb <= b1; bar++) {
			const x = X(bar * bpb);
			g.fillStyle = line; g.fillRect(x, bar % every === 0 ? 4 : 14, 1, RULER - (bar % every === 0 ? 4 : 14));
			if (bar % every === 0) { g.fillStyle = muted; g.fillText(String(bar + 1), x + 4, RULER / 2 + 1); }
		}
		// sections
		d.markers.forEach((m, i) => {
			const x0 = X(m.beat), x1 = X(d.markers[i + 1]?.beat ?? d.endBeat);
			if (x1 < HEAD || x0 > w) return;
			g.fillStyle = i % 2 ? alpha(accent, 0.1) : alpha(accent, 0.18);
			g.fillRect(x0, RULER, x1 - x0, SECT);
			g.fillStyle = text; g.font = '600 11px "Instrument Sans", sans-serif';
			g.save(); g.beginPath(); g.rect(x0, RULER, x1 - x0, SECT); g.clip(); g.fillText(m.name, Math.max(x0, HEAD) + 5, RULER + SECT / 2 + 1); g.restore();
		});
		// chords from lint --harmony
		const hb = E.harmony?.bars || [];
		const bad = new Set(), rub = new Set();
		(E.harmony?.problems || []).forEach(p => { for (let b = p.bars[0]; b <= p.bars[1]; b++) bad.add(b); });
		(E.harmony?.rubs || []).forEach(r => r.bars.forEach(b => rub.add(b)));
		g.font = '11px "JetBrains Mono", monospace';
		for (const row of hb) {
			const x0 = X((row.bar - 1) * bpb), x1 = X(row.bar * bpb), y = RULER + SECT;
			if (x1 < HEAD || x0 > w) continue;
			if (bad.has(row.bar) || row.outside) { g.fillStyle = alpha('#e5484d', .3); g.fillRect(x0, y, x1 - x0, CHORD); }
			else if (rub.has(row.bar)) { g.fillStyle = alpha('#f2b33d', .32); g.fillRect(x0, y, x1 - x0, CHORD); }
			const label = row.halves ? row.halves.join(' ') : row.chord;
			if (g.measureText(label).width < x1 - x0 - 4) { g.fillStyle = text; g.fillText(label, x0 + 3, y + CHORD / 2 + 1); }
			g.fillStyle = line; g.fillRect(x0, y + 4, 1, CHORD - 8);
		}
		// comment pins
		E.comments.forEach(c => {
			if (!c.beats) return;
			const x = X(c.beats[0]);
			if (x < HEAD - 6 || x > w + 6) return;
			g.fillStyle = c.status === 'done' ? muted : accent;
			g.beginPath(); g.moveTo(x, RULER - 2); g.lineTo(x - 5, 4); g.lineTo(x + 5, 4); g.closePath(); g.fill();
		});
		g.fillStyle = line; g.fillRect(HEAD, RULER, w - HEAD, 1); g.fillRect(HEAD, RULER + SECT, w - HEAD, 1); g.fillRect(HEAD, TOPH - 1, w - HEAD, 1);
		g.restore();

		// ---- playhead ----
		if (audio.src && audio.duration) {
			const x = X(audioBeat());
			if (x >= HEAD) { g.fillStyle = v('--play'); g.fillRect(x - 1, 0, 2, h); }
		}
		if (E.loop && E.sel.b0 != null) {
			g.fillStyle = accent; g.font = '600 10px "Instrument Sans", sans-serif'; g.textBaseline = 'alphabetic';
			const x = Math.max(HEAD + 4, X(E.sel.b0) + 4); g.fillText('LOOP', x, TOPH - 5);
		}

		// ---- frozen header column ----
		g.textBaseline = 'alphabetic';
		g.fillStyle = v('--panel'); g.fillRect(0, 0, HEAD, h);
		g.save(); g.beginPath(); g.rect(0, TOPH, HEAD, h - TOPH); g.clip();
		top = TOPH - sy;
		d.tracks.forEach((t, i) => {
			const lh = laneH(i);
			if (top + lh > TOPH && top < h) {
				const selT = E.sel.tracks.has(i), solo = state.soloIdx === i;
				if (selT) { g.fillStyle = alpha(accent, 0.12); g.fillRect(0, top, HEAD, lh); }
				g.fillStyle = hue(i); g.fillRect(0, top + 4, 3, lh - 8);
				g.fillStyle = muted; g.font = '11px "Instrument Sans", sans-serif'; g.fillText(E.expanded.has(i) ? '▾' : '▸', 9, top + 16);
				g.fillStyle = selT ? accent : text; g.font = '600 12.5px "Instrument Sans", sans-serif';
				clipText(g, (t.mute ? '(m) ' : '') + t.name, 22, top + 16, HEAD - 64);
				g.fillStyle = muted; g.font = '10.5px "Instrument Sans", sans-serif';
				clipText(g, soundName(t), 22, top + 31, HEAD - 104);
				if (t.lufs != null) {   // stem loudness, right-aligned left of the solo button
					g.font = '10.5px "JetBrains Mono", monospace'; g.textAlign = 'right';
					g.fillText(t.lufs <= -100 ? 'silent' : t.lufs.toFixed(1), HEAD - 38, top + 31); g.textAlign = 'left';
				}
				// solo button: filled = solo in the mix, outlined D = dry stem, amber dots = rendering
				const bx = HEAD - 32, by = top + 11, pend = state.pending?.i === i, dry = solo && state.soloKind === 'dry';
				g.fillStyle = pend ? alpha('#f2b33d', .25) : solo && !dry ? v('--button') : v('--panel-2');
				g.strokeStyle = pend ? '#f2b33d' : solo && !dry ? v('--button') : solo ? accent : line; g.lineWidth = 1;
				roundRect(g, bx, by, 24, 20, 5); g.fill(); g.stroke();
				g.fillStyle = pend ? '#f2b33d' : solo && !dry ? '#fff' : solo ? accent : text; g.font = '600 10.5px "Instrument Sans", sans-serif';
				g.textAlign = 'center';
				g.fillText(pend ? '•'.repeat(1 + Math.floor(performance.now() / 350) % 3) : dry ? 'D' : 'S', bx + 12, by + 14);
				g.textAlign = 'left';
				if (E.expanded.has(i)) {   // note names down the side of an open lane
					const kg = keyGeom(t, top, lh);
					g.font = '9.5px "JetBrains Mono", monospace'; g.fillStyle = muted;
					for (let k = kg.lo; k <= kg.hi; k++) {
						const y = kg.y(k) + kg.row;
						if (y > top + 40 && (k % 12 === 0 || (kg.row >= 9 && [4, 7].includes(k % 12)))) g.fillText(keyName(k), HEAD - 34, y);
					}
				}
				g.fillStyle = line; g.fillRect(0, top + lh - 1, HEAD, 1);
			}
			top += lh;
		});
		g.restore();
		// corner: key(s) of the song
		g.fillStyle = v('--panel-2'); g.fillRect(0, 0, HEAD, TOPH);
		g.fillStyle = muted; g.font = '10.5px "Instrument Sans", sans-serif';
		g.fillText('BAR', 12, 16); g.fillText('SECTION', 12, RULER + 14); g.fillText('CHORD', 12, RULER + SECT + 16);
		const keys = E.harmony?.keys || [];
		g.fillStyle = text; g.font = '600 11px "Instrument Sans", sans-serif';
		if (keys.length) clipText(g, keys.map(k => k.key).join(' → '), 70, RULER + SECT + 16, HEAD - 78);
		g.fillStyle = line; g.fillRect(HEAD - 1, 0, 1, h); g.fillRect(0, TOPH - 1, HEAD, 1);
		// drag rectangle
		if (E.drag?.kind === 'marquee' && E.drag.moved) {
			const r = E.drag; g.strokeStyle = accent; g.setLineDash([4, 3]); g.lineWidth = 1;
			g.strokeRect(Math.min(r.x0, r.x1), Math.min(r.y0, r.y1), Math.abs(r.x1 - r.x0), Math.abs(r.y1 - r.y0)); g.setLineDash([]);
		}
	}
	function gridLines(g, b0, b1, y0, y1, v) {
		const bpb = E.data.bpb, beats = E.zoom >= 10;
		for (let b = Math.floor(b0); b <= b1; b++) {
			const isBar = Math.abs(b / bpb - Math.round(b / bpb)) < 1e-6;
			if (!isBar && !beats) continue;
			g.fillStyle = isBar ? v('--line') : v('--grid');
			g.fillRect(X(b), y0, 1, y1 - y0);
		}
	}
	// the sound a track plays: preset or kit name, without folders, extensions or palette suffixes
	function soundName(t) {
		const raw = String(t.preset || t.plugin || '');
		return raw.split('/').pop().replace(/\.(vstpreset|clap-preset|state|fxb|fxp|vital|json)$/i, '').replace(/--.*$/, '') || t.plugin;
	}
	function clipText(g, s, x, y, max) {
		if (g.measureText(s).width <= max) { g.fillText(s, x, y); return; }
		while (s.length > 1 && g.measureText(s + '…').width > max) s = s.slice(0, -1);
		g.fillText(s + '…', x, y);
	}
	function roundRect(g, x, y, w, h, r) { g.beginPath(); g.moveTo(x + r, y); g.arcTo(x + w, y, x + w, y + h, r); g.arcTo(x + w, y + h, x, y + h, r); g.arcTo(x, y + h, x, y, r); g.arcTo(x, y, x + w, y, r); g.closePath(); }

	/* ---------- hit testing ---------- */
	function noteAt(p) {
		const lane = laneAt(p.y + scroller.scrollTop);
		if (!lane || p.x < HEAD || p.y < TOPH) return null;
		const t = E.data.tracks[lane.i], kg = keyGeom(t, lane.top - scroller.scrollTop, lane.h), b = beatAt(p.x);
		let best = null, bd = 1e9;
		t.beatsNotes.forEach((n, idx) => {
			if (b < n[0] - 2 / E.zoom || b > n[0] + n[1] + 2 / E.zoom) return;
			const y = kg.y(n[2]), dy = p.y < y ? y - p.y : p.y > y + kg.row ? p.y - y - kg.row : 0;
			if (dy < Math.max(4, kg.row) && dy < bd) { bd = dy; best = { t: lane.i, n: idx }; }
		});
		return best;
	}

	/* ---------- mouse ---------- */
	function down(e) {
		if (e.button !== 0) return;
		const p = pos(e), d = E.data; if (!d) return;
		if (p.x < HEAD && p.y >= TOPH) {   // header column
			const lane = laneAt(p.y + scroller.scrollTop); if (!lane) return;
			const i = lane.i, ly = p.y + scroller.scrollTop - lane.top;
			if (p.x >= HEAD - 34 && ly >= 8 && ly < 34) { toggleSolo(i, e.altKey ? 'dry' : 'mix'); syncAudioSelect(); dirty(); return; }
			if (p.x < 20) { E.expanded.has(i) ? E.expanded.delete(i) : E.expanded.add(i); sizeSpace(); dirty(); return; }
			if (e.shiftKey || e.metaKey) E.sel.tracks.has(i) ? E.sel.tracks.delete(i) : E.sel.tracks.add(i);
			else { E.sel.tracks = new Set([i]); }
			selChanged(); return;
		}
		if (p.x >= HEAD && p.y < TOPH) {   // ruler / sections / chords: drag = bars, click = seek
			E.drag = { kind: 'bars', b: beatAt(p.x), x0: p.x, moved: false };
			return;
		}
		if (p.x >= HEAD && p.y >= TOPH) {
			const hit = noteAt(p);
			if (hit) {
				const has = E.sel.notes.findIndex(q => q.t === hit.t && q.n === hit.n);
				if (e.shiftKey || e.metaKey) { has >= 0 ? E.sel.notes.splice(has, 1) : E.sel.notes.push(hit); }
				else E.sel.notes = [hit];
				barsFromNotes(); selChanged(); return;
			}
			E.drag = { kind: 'marquee', x0: p.x, y0: p.y, x1: p.x, y1: p.y, moved: false, add: e.shiftKey || e.metaKey };
		}
	}
	function move(e) {
		if (!dlg?.open || !E.data) return;
		const p = pos(e);
		if (E.drag) {
			if (Math.abs(p.x - (E.drag.x0)) > 3) E.drag.moved = true;
			if (E.drag.kind === 'bars' && E.drag.moved) {
				const a = E.drag.b, b = beatAt(p.x), bpb = E.data.bpb;
				E.sel.b0 = Math.floor(Math.min(a, b) / bpb) * bpb; E.sel.b1 = Math.ceil(Math.max(a, b) / bpb + 1e-9) * bpb;
				if (E.sel.b1 === E.sel.b0) E.sel.b1 += bpb;
				selChanged(false);
			}
			if (E.drag.kind === 'marquee') { E.drag.x1 = p.x; E.drag.y1 = p.y; if (Math.abs(p.y - E.drag.y0) > 3) E.drag.moved = true; dirty(); }
			autoscroll(p);
			return;
		}
		// hover tooltip
		const r = canvas.getBoundingClientRect();
		if (p.cx < r.left || p.cx > r.right || p.cy < r.top || p.cy > r.bottom) return;
		let html = '';
		if (p.x < HEAD && p.y >= TOPH) {
			const lane = laneAt(p.y + scroller.scrollTop);
			if (lane) {
				const ly = p.y + scroller.scrollTop - lane.top, t = E.data.tracks[lane.i];
				if (p.x >= HEAD - 34 && ly >= 8 && ly < 34) {
					const pend = state.pending?.i === lane.i;
					html = pend ? `Rendering ${esc(t.name)} through the mix (sends, buses, master)… ${Math.round((Date.now() - state.pending.since) / 1000)}s<br>it plays when ready; click again to cancel`
						: state.soloIdx === lane.i ? `Playing ${esc(t.name)} ${state.soloKind === 'dry' ? 'dry (its stem)' : 'in the mix'}; click to go back to the full mix`
						: `Solo ${esc(t.name)} in the mix, the whole song (renders once, then cached)<br>quicker: select bars and use Solo track or ▶ Preview<br>Alt+click: the dry stem, instantly`;
				}
			}
		} else if (p.x >= HEAD && p.y >= TOPH) {
			const hit = noteAt(p);
			if (hit) {
				const t = E.data.tracks[hit.t], n = t.beatsNotes[hit.n];
				html = `${esc(t.name)} · ${keyName(n[2])}<br>bar ${barBeat(n[0])} · ${+n[1].toFixed(3)} beats · vel ${Math.round(n[3] * 100)}`;
			} else html = `bar ${barBeat(beatAt(p.x))}`;
		} else if (p.x >= HEAD && p.y < TOPH) {
			const bar = barOf(beatAt(p.x)), row = E.harmony?.bars?.find(b => b.bar === bar);
			const probs = (E.harmony?.problems || []).filter(q => bar >= q.bars[0] && bar <= q.bars[1]);
			const rubs = (E.harmony?.rubs || []).filter(q => q.bars.includes(bar));
			const cs = E.comments.filter(c => c.bars && bar >= c.bars[0] && bar <= c.bars[1]);
			html = `bar ${bar} · ${fmtTime(E.data.toSec((bar - 1) * E.data.bpb))}${row ? ' · ' + esc(row.chord) + (row.key ? ' in ' + esc(row.key) : '') : ''}`
				+ probs.map(q => '<br>⚠ ' + esc(q.detail.split(':')[0])).join('')
				+ rubs.map(q => '<br>rub: ' + esc(q.tracks.join(' / ')) + ' ' + esc(q.example)).join('')
				+ cs.map(c => '<br>💬 ' + esc(c.text.slice(0, 70))).join('');
		}
		if (html) {
			tip.innerHTML = html; tip.hidden = false;
			const mr = dlg.querySelector('.ed-main').getBoundingClientRect();
			tip.style.left = Math.min(p.cx - mr.left + 14, mr.width - tip.offsetWidth - 8) + 'px';
			tip.style.top = (p.cy - mr.top + 16) + 'px';
		} else tip.hidden = true;
	}
	function up(e) {
		if (!E.drag) return;
		const dr = E.drag; E.drag = null;
		if (dr.kind === 'bars' && !dr.moved) { seekBeat(dr.b, false); return; }
		if (dr.kind === 'marquee') {
			if (!dr.moved) {   // click on an empty spot: that bar, that track
				const lane = laneAt(dr.y0 + scroller.scrollTop), b = beatAt(dr.x0), bpb = E.data.bpb;
				E.sel = { b0: Math.floor(b / bpb) * bpb, b1: Math.floor(b / bpb) * bpb + bpb, tracks: new Set(lane ? [lane.i] : []), notes: [] };
				selChanged(); return;
			}
			const bx0 = beatAt(Math.min(dr.x0, dr.x1)), bx1 = beatAt(Math.max(dr.x0, dr.x1));
			const ya = Math.min(dr.y0, dr.y1), yb = Math.max(dr.y0, dr.y1);
			const picked = dr.add ? [...E.sel.notes] : [];
			E.data.tracks.forEach((t, i) => {
				const top = laneTop(i) - scroller.scrollTop, lh = laneH(i);
				if (top + lh < ya || top > yb) return;
				const kg = keyGeom(t, top, lh);
				t.beatsNotes.forEach((n, idx) => {
					const y = kg.y(n[2]);
					if (n[0] + n[1] > bx0 && n[0] < bx1 && y + kg.row >= ya && y <= yb && !picked.some(q => q.t === i && q.n === idx)) picked.push({ t: i, n: idx });
				});
			});
			E.sel.notes = picked; barsFromNotes(); selChanged();
		}
	}
	function autoscroll(p) {
		const w = scroller.clientWidth;
		if (p.x > w - 30) scroller.scrollLeft += 18; else if (p.x < HEAD + 10 && scroller.scrollLeft > 0) scroller.scrollLeft -= 18;
	}
	function barsFromNotes() {
		if (!E.sel.notes.length) return;
		const bpb = E.data.bpb, ns = E.sel.notes.map(q => E.data.tracks[q.t].beatsNotes[q.n]);
		E.sel.b0 = Math.floor(Math.min(...ns.map(n => n[0])) / bpb + 1e-9) * bpb;
		E.sel.b1 = Math.ceil(Math.max(...ns.map(n => n[0] + n[1])) / bpb - 1e-9) * bpb;
		if (E.sel.b1 <= E.sel.b0) E.sel.b1 = E.sel.b0 + bpb;
		E.sel.tracks = new Set(E.sel.notes.map(q => q.t));
	}
	function clearSel() { E.sel = { b0: null, b1: null, tracks: new Set(), notes: [] }; setLoop(false); selChanged(); }

	/* ---------- selection summary / reference ---------- */
	function reference() {
		const d = E.data, s = E.sel, out = { text: '' };
		if (!d || (s.b0 == null && !s.tracks.size && !s.notes.length)) return out;
		const lines = [];
		if (s.b0 != null) {
			const a = barOf(s.b0), b = barOf(s.b1 - 1e-6);
			out.bars = [a, b]; out.beats = [s.b0, s.b1];
			out.time = [+(d.toSec(s.b0)).toFixed(2), +(d.toSec(s.b1)).toFixed(2)];
			const sec = d.markers.filter(m => m.beat < s.b1 && (d.markers[d.markers.indexOf(m) + 1]?.beat ?? 1e9) > s.b0).map(m => m.name);
			lines.push((a === b ? 'bar ' + a : 'bars ' + a + '-' + b) + ' · ' + fmtTime(out.time[0]) + '-' + fmtTime(out.time[1]) + (sec.length ? ' · ' + sec.join(', ') : ''));
			const chords = (E.harmony?.bars || []).filter(r => r.bar >= a && r.bar <= b).map(r => r.halves ? r.halves.join('>') : r.chord);
			if (chords.length && chords.length <= 16) lines.push('chords: ' + chords.join(' '));
		}
		if (s.tracks.size) { out.tracks = [...s.tracks].map(i => d.tracks[i].name); lines.push('tracks: ' + out.tracks.join(', ')); }
		if (s.notes.length) {
			out.notes = s.notes.slice(0, 64).map(q => { const t = d.tracks[q.t], n = t.beatsNotes[q.n]; return { track: t.name, key: keyName(n[2]), midi: n[2], bar: barBeat(n[0]), beat: n[0], dur: n[1], vel: n[3] }; });
			const shown = out.notes.slice(0, 8).map(n => `${n.track} ${n.key} @${n.bar}`);
			lines.push('notes: ' + shown.join(', ') + (s.notes.length > 8 ? ` (+${s.notes.length - 8} more)` : ''));
		}
		out.ref = lines[0] + (out.tracks ? ' · ' + out.tracks.join(', ') : '');
		out.text = state.slug + ' · ' + lines.join('\n');
		return out;
	}
	function selChanged(redrawSide = true) {
		const r = reference(), el = $d('#ed-ref'), any = !!r.text;
		el.classList.toggle('none', !any);
		el.textContent = any ? r.text.replace(state.slug + ' · ', '') : 'Drag across the ruler to pick bars, click a track name, click or drag over notes.';
		$d('#ed-sloop').disabled = E.sel.b0 == null;
		$d('#ed-preview').disabled = E.sel.b0 == null;
		$d('#ed-preview').textContent = E.sel.b0 == null ? '▶ Preview these bars' : E.sel.tracks.size ? `▶ Preview ${E.sel.tracks.size === 1 ? E.data.tracks[[...E.sel.tracks][0]].name : E.sel.tracks.size + ' tracks'} here` : '▶ Preview these bars';
		$d('#ed-solo').disabled = !(E.sel.tracks.size || E.sel.notes.length);
		$d('#ed-copy').disabled = !any;
		if (!any && E.loop) setLoop(false);
		dirty();
	}
	// render the selected bars (and the selected tracks, or `names`) through the mix, then loop them
	function previewSelection(names) {
		if (!E.data || E.sel.b0 == null) return;
		const a = barOf(E.sel.b0), b = barOf(E.sel.b1 - 1e-6);
		const tracks = Array.isArray(names) ? names : [...E.sel.tracks].map(i => E.data.tracks[i].name);
		const one = tracks.length === 1 ? E.data.tracks.findIndex(t => t.name === tracks[0]) : null;
		requestPreview({ tracks, from: a, to: b + 1, i: one ?? undefined,
			label: (tracks.length ? tracks.join(', ') + ' in ' : '') + (a === b ? 'bar ' + a : 'bars ' + a + '-' + b) });
		dirty();
	}
	function setLoop(on) {
		E.loop = on && E.sel.b0 != null;
		$d('#ed-loop').classList.toggle('on', E.loop);
		dirty();
	}

	/* ---------- comments ---------- */
	async function save() {
		const text = $d('#ed-text').value.trim();
		if (!text) { $d('#ed-text').focus(); return; }
		const r = reference();
		const body = { op: 'add', text, ref: r.ref || 'whole song', render: state.song.reportPath ? state.files[state.song.reportPath]?.[1] : null };
		for (const k of ['bars', 'beats', 'time', 'tracks', 'notes']) if (r[k]) body[k] = r[k];
		const res = await fetch('api/review?song=' + encodeURIComponent(state.slug), { method: 'POST', headers: postHeaders(), body: JSON.stringify(body) }).then(r => r.json());
		if (res.comments) { E.comments = res.comments; $d('#ed-text').value = ''; renderComments(); badge(); dirty(); }
	}
	async function op(body) {
		const res = await fetch('api/review?song=' + encodeURIComponent(state.slug), { method: 'POST', headers: postHeaders(), body: JSON.stringify(body) }).then(r => r.json());
		if (res.comments) { E.comments = res.comments; renderComments(); badge(); dirty(); }
	}
	function renderComments() {
		if (!dlg) return;
		const list = [...E.comments].sort((a, b) => (a.status === 'done') - (b.status === 'done') || (a.beats?.[0] ?? 0) - (b.beats?.[0] ?? 0));
		const open = E.comments.filter(c => c.status !== 'done').length;
		$d('#ed-count').textContent = E.comments.length ? `${open} open · ${E.comments.length - open} done` : '';
		$d('#ed-list').innerHTML = list.map(c => `
			<div class="ed-c ${c.status === 'done' ? 'done' : ''}" data-id="${esc(c.id)}">
				<div class="ref">${esc(c.ref || 'whole song')}</div>
				<p>${esc(c.text)}</p>${c.reply ? `<p style="border-left:2px solid var(--accent-2);padding-left:8px;color:var(--muted);font-size:12.5px">Agent: ${esc(c.reply)}</p>` : ''}
				<div class="meta"><span>${new Date(c.created).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span><span class="sp"></span>
					<button data-act="status">${c.status === 'done' ? 'Reopen' : 'Mark done'}</button><button data-act="delete">Delete</button></div>
			</div>`).join('') || '<div class="ed-empty">No comments yet. Select something, write what should change, save.</div>';
	}
	function badge() {
		const b = document.getElementById('ed-badge'); if (!b) return;
		const open = E.comments.filter(c => c.status !== 'done').length;
		b.hidden = !open; b.textContent = open;
	}
	function legend() {
		if (!dlg) return;
		const h = E.harmony;
		const probs = h ? h.problems.length : 0, rubs = h ? h.rubs.reduce((n, r) => n + r.count, 0) : 0;
		$d('#ed-legend').innerHTML = h ? `<span><i style="background:color-mix(in srgb,#e5484d 45%,transparent)"></i>${probs} harmony problem${probs === 1 ? '' : 's'}</span><span><i style="background:color-mix(in srgb,#f2b33d 45%,transparent)"></i>${rubs} rub${rubs === 1 ? '' : 's'}</span>` : '';
	}

	/* ---------- zoom, keys, audio ---------- */
	function zoomAt(f, at) {
		const x = at ?? scroller.clientWidth / 2, b = beatAt(x);
		E.zoom = Math.max(1.5, Math.min(160, E.zoom * f));
		sizeSpace();
		scroller.scrollLeft = HEAD + b * E.zoom - x;
		dirty();
	}
	function fit() { if (!E.data) return; E.zoom = Math.max(1.5, (scroller.clientWidth - HEAD - 30) / E.data.endBeat); sizeSpace(); scroller.scrollLeft = 0; dirty(); }
	function key(e) {
		if (e.target.tagName === 'TEXTAREA' || e.target.tagName === 'SELECT') return;
		if (e.code === 'Space') { e.preventDefault(); $d('#ed-play').click(); }
		else if (e.key === 'l' || e.key === 'L') setLoop(!E.loop);
		else if (e.key === 'p' || e.key === 'P') previewSelection();
		else if (e.key === '+' || e.key === '=') zoomAt(1.4);
		else if (e.key === '-') zoomAt(1 / 1.4);
		else if (e.key === 'f' || e.key === 'F') fit();
		else if (e.key === 'c' || e.key === 'C') { e.preventDefault(); $d('#ed-text').focus(); }
	}
	function syncAudioSelect() {
		const sel = $d('#ed-audio'), d = state.song;
		const opts = (d.audio || []).map(p => `<option value="${esc(p)}">${esc(p.split('/').pop())}</option>`);
		if (d.reportPath) {
			opts.push('<optgroup label="Solo in the mix (sends, buses, master)">');
			(E.data?.tracks || []).forEach((t, i) => opts.push(`<option value="solo:${i}">${esc(t.name)}</option>`));
			opts.push('</optgroup>');
		}
		const dry = (E.data?.tracks || []).map((t, i) => stemFor(i) ? `<option value="stem:${i}">${esc(t.name)}</option>` : '').join('');
		if (dry) opts.push(`<optgroup label="Dry stems (before fader, sends, master)">${dry}</optgroup>`);
		sel.innerHTML = opts.join('') || '<option>no audio yet</option>';
		if (state.preview) opts.unshift(`<option value="preview">Preview: ${esc(state.preview.label)}</option>`);
		sel.innerHTML = opts.join('') || '<option>no audio yet</option>';
		sel.value = state.preview ? 'preview' : state.soloIdx >= 0 ? (state.soloKind === 'dry' ? 'stem:' : 'solo:') + state.soloIdx : (state.src || '');
	}

	/* ---------- frame loop: playhead, loop, follow ---------- */
	(function frame() {
		if (dlg?.open && E.data) {
			if (!audio.paused) {
				const b = audioBeat();
				if (E.loop && !state.srcWindow && E.sel.b0 != null && (b >= E.sel.b1 || b < E.sel.b0 - E.data.bpb)) seekBeat(E.sel.b0, false);
				if (E.follow && performance.now() - E.userScrollAt > 2500 && !E.drag) {
					const x = X(b), w = scroller.clientWidth;
					if (x > w - 60 || x < HEAD) scroller.scrollLeft = HEAD + b * E.zoom - HEAD - (w - HEAD) * 0.15;
				}
				const s = songSecNow(), ab = audioBeat(), bar = barOf(ab), beat = Math.floor(ab - (bar - 1) * E.data.bpb + 1e-9) + 1;
				$d('#ed-clock').innerHTML = `${fmtTime(Math.max(0, s))} / ${fmtTime(E.data.toSec(E.data.endBeat))}<small>bar ${bar} · beat ${beat}${s < 0 ? ' (lead-in)' : state.srcWindow ? ' · preview' : ''}</small>`;
				E.dirty = true;
			}
			if (state.pending) E.dirty = true;   // the rendering dots on the solo button
			const st = $d('#ed-status'), msg = document.getElementById('solo').textContent;
			if (st.textContent !== msg || st.classList.contains('busy') !== !!state.pending) { st.textContent = msg; st.title = msg + (state.srcWindow ? '\nclick the timeline outside the preview, or pick the mix, to go back' : ''); st.classList.toggle('busy', !!state.pending); }
			if (E.dirty) { E.dirty = false; draw(); }
		}
		requestAnimationFrame(frame);
	})();

	/* ---------- public ---------- */
	window.WLEditor = {
		open(atBeat) {
			if (!state.song?.job) return;
			if (!dlg) build();
			$d('#ed-title').textContent = state.slug;
			prepare(); sizeSpace(); syncAudioSelect(); renderComments(); selChanged(); icon();
			dlg.showModal();
			requestAnimationFrame(() => {
				if (E.fitted !== state.slug || E.zoom * E.data.endBeat < scroller.clientWidth - HEAD) { fit(); E.fitted = state.slug; }   // a new song opens showing all of it
				if (atBeat != null) scroller.scrollLeft = Math.max(0, atBeat * E.zoom - 200);
				dirty();
			});
			loadExtras();
		},
		refresh() {   // the song was re-rendered or its job changed
			if (dlg?.open) { prepare(); sizeSpace(); syncAudioSelect(); dirty(); loadExtras(); }
			else fetch('api/review?song=' + encodeURIComponent(state.slug)).then(r => r.json()).then(r => { E.comments = r.comments || []; badge(); }).catch(() => {});
		},
		redraw() { dirty(); if (dlg?.open) syncAudioSelect(); },
		reset() { E.sel = { b0: null, b1: null, tracks: new Set(), notes: [] }; E.expanded = new Set(); E.harmony = null; E.comments = []; E.loop = false; badge(); },
	};
})();
